version: "3"

services:
  axon-server:
    # docker run -d --name my-axon-server -p 8024:8024 -p 8124:8124 axoniq/axonserver
    image: axoniq/axonserver
    container_name: axon-server
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
    ports:
      - 8024:8024
      - 8124:8124